name: Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Install libs
      run: |
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib install hxcpp

    - name: Build APK
      run: |
        lime build android
