 name: Android APK

 on:
  workflow_dispatch:

 jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Install Haxelib libraries
      run: |
        yes | haxelib install lime
        yes | haxelib install openfl
        yes | haxelib install flixel
        yes | haxelib install flixel-addons
        yes | haxelib install flixel-ui
        yes | haxelib install hxcpp
        yes | haxelib install actuate
        yes | haxelib install tjson

    - name: Install linc_luajit
      run: |
        git clone 
        https://github.com/superpowers04/linc_luajit.git
        haxelib dev linc_luajit linc_luajit
        
    - name: Setup Lime
      run: |
        haxelib run lime setup

    - name: Build APK
      run: |
        haxelib run lime build android
