 name: Android APK

 on:
  workflow_dispatch:

 jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Install Haxelib libraries
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install flixel --quiet
        haxelib install flixel-addons --quiet
        haxelib install flixel-ui --quiet
        haxelib install hxcpp --quiet
        haxelib install actuate --quiet
        haxelib install tjson --quiet

    - name: Setup Lime
      run: |
        haxelib run lime setup

    - name: Build APK
      run: |
        haxelib run lime build android
